# Site identity
title:              Rohan Ippalapally
email:              irohan90839@gmail.com
description:        Machine Learning Engineer focused on edge AI, computer vision, NLP, and MLOps.
author:             Rohan Ippalapally
baseurl:            "/"
url:                "https://irohan98.github.io"

# Social profiles used by templates
github_username:    irohan98
linkedin_username:  rohan-ippalapally

# Add your Google Analytics ID here to activate analytics
google_analytics:   UA-XXXXXXXXX-X # put your google-analytics code

# Build settings for Jekyll
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
